#!/bin/bash

REPO="https://raw.githubusercontent.com/izzstores/scizz/main/"
mkdir -p /usr/local/xdxl/
wget -q -O /usr/local/xdxl/badvpn-udpgpw "${REPO}badvpn/badvpn-udpgpw"
chmod +x /usr/local/xdxl/badvpn-udpgpw
wget -q -O /etc/systemd/system/badvpn1.service "${REPO}badvpn/badvpn-1.service"
wget -q -O /etc/systemd/system/badvpn2.service "${REPO}badvpn/badvpn-2.service"
wget -q -O /etc/systemd/system/badvpn3.service "${REPO}badvpn/badvpn-3.service"
wget -q -O /etc/systemd/system/badvpn4.service "${REPO}badvpn/badvpn-4.service"
wget -q -O /etc/systemd/system/badvpn5.service "${REPO}badvpn/badvpn-5.service"

systemctl disable badvpn1
systemctl stop badvpn1
systemctl enable badvpn1
systemctl start badvpn1

systemctl disable badvpn2
systemctl stop badvpn2
systemctl enable badvpn2
systemctl start badvpn2

systemctl disable badvpn3
systemctl stop badvpn3
systemctl enable badvpn3
systemctl start badvpn3

systemctl disable badvpn4
systemctl stop badvpn4
systemctl enable badvpn4
systemctl start badvpn4

systemctl disable badvpn5
systemctl stop badvpn5
systemctl enable badvpn5
systemctl start badvpn5
